### ISSUE TITLE
.env.development 是否可以配置为.env.dev

### ISSUE THREAD

**Issue by huoxudong125** [WellerQu/vscode-env-cmd-file-syntax#3]
`.env.development` 是否可以配置为`.env.dev`，`.env.prod`,如果能够配置那就更好了

**Comment by WellerQu** [comment]
sorry, 还不能. 我是依照 https://create-react-app.dev/docs/adding-custom-environment-variables#what-other-env-files-can-be-used 这个文档来约定文件名的. 如果这个需求很有必要的话, 我可以改一改. 

说实话, 我也觉得 .env.development 很长.

**Comment by lshz0088** [comment]
@WellerQu 请问这功能有了么，我也比较需要，因为现在有很多环境的配置文件，名称都不一样。默认的不够用了

**Comment by WellerQu** [comment]
> @WellerQu 请问这功能有了么，我也比较需要，因为现在有很多环境的配置文件，名称都不一样。默认的不够用了

老铁, 不是我懒, 是您这个需求没办法满足(我理解的您的需求是需要无穷个.env文件), 但是您看到package.json文件的"extensions"节点:

```json
"extensions": [
  ".env",
  ".development",
  ".local",
  ".test",
  ".production"
],
```

实际上是个有限集合. 以上述任何一个扩展名结尾都行. 我实在不敢想象, 您会有5的阶乘(5!)个环境配置文件 ? 还是我理解错了?

期待您的回复.
